---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function from Cloud Formation by Wolfgang Unger'

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            ZipFile: >
                def lambda_handler(event, context):
                return 'Hello from Lambda'
        Description: Test with Cloud Formation
        FunctionName: wu-HelloWorldPyByCF
        Handler: index.lambda_handler
        #Role: arn:aws:iam::016973021151:role/service-role/LambdaRole
        Role: arn:aws:iam::563703158576:role/wur-LambdaRole
        
        Runtime: python2.7

